spring:
  application:
    name: pdf-report-service
activemq:
  url: tcp://localhost:61616
  username: admin
  password: ENC(anz73AIkhRw+cNLFhp+oqw==)
  queue:
    processing: processing
ftp:
  host: localhost
  port: 21
  username: admin
  password: ENC(anz73AIkhRw+cNLFhp+oqw==)

fetch:
  size:
    movie: 50
thread:
  pool:
    initial: 16
    max: 64

request:
  date:
    format: yyyy-MM-dd HH:mm:ss

logging.level.com.dzytsiuk.pdfreportservice.service.impl.client.MovielandClient: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
